#define MBEDTLS_SHA256_C
#define MBEDTLS_AES_C
#define MBEDTLS_MD_C
#define MBEDTLS_CIPHER_MODE_CBC

#define MBEDTLS_SSL_TLS_C
// #define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SHA256_C
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_PROTO_DTLS

#define MBEDTLS_BIGNUM_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PEM_PARSE_C
 